require 'rexml/document'
include REXML
require "protocol_object.rb"
require "helper.rb"
require "parser.rb"
require "render.rb"
require "protocol.rb"
require "role.rb"
require "condition.rb"
require "action.rb"
require "message"
require "state"
require "init_state"
require "rule"
